#!/bin/bash
#
# chasset: tool for changing asset entry
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: chasset 181 2023-04-19 21:37:20Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

showinfo "Setting asset tag to \"$*\""
tmpfile=$(mktemp)
echo '
	{
	  "Server":{
	    "SystemConfig":{
	      "IrmcConfig":{
		"@Processing":"execute",
		"System":{
		  "AssetTag":"'$*'"
		},
		"@Version":"1.04"
	      }
	    },
	    "@Version":"1.01"
	  }
	}
' >$tmpfile
${0%/*}/restsetprofile $tmpfile 
#${0%/*}/restsetprofile -i $IRMC -u $USER -p "$PW" $tmpfile 
rm $tmpfile
