#!/bin/bash
#
# restdeleteci: Delete custom images on eLCM
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restdeleteci 70 2020-08-11 05:59:24Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

showinfo "Deleting custom image >${1:-$CUSTOMIMAGENAME}< on $IRMC ..."
CustomImageDelete ${1:-$CUSTOMIMAGENAME} >/dev/null
showinfo "Done"
