#!/bin/bash
#
# restgetci: List existing custom images on eLCM
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restlistci 70 2020-08-11 05:59:24Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

showinfo "Restrieving available custom images on $IRMC ..."
RestGet rest/v1/Oem/eLCM/CustomImage | grep odata | sed 's/.*\/// 
				         	         s/"//'
