#!/bin/bash
#
# restuploadci - Tool for uploading custom image to eLCM
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restuploadci 56 2020-08-05 08:30:39Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

IMAGE=${1:-${CUSTOMIMAGEURLPATH}/${CUSTOMIMAGENAME}.${CUSTOMIMAGESUFFIX}}

# Some convenience
scheme=${IMAGE%%:*}; [ "${scheme/https/http}" = http ] || IMAGE=${CUSTOMIMAGEURLPATH}/$IMAGE
[ "${IMAGE##*.}" = iso ] || IMAGE=${IMAGE}.${CUSTOMIMAGESUFFIX}

showinfo Uploading $IMAGE to $IRMC
SESSION=$(CustomImageUpload $IMAGE)
[ -z "$SESSION" ] && error 1 CustomImageUpload failed
showinfo Waiting for session $SESSION to terminate - be patient ...
SessionWait $SESSION
showinfo Done
# Delete session from session list
showinfo Cleaning up
SessionDelete $SESSION >/dev/null
