#!/bin/bash
#
# restsetprofile: tool for assigning a iRMC/BIOS profile via RESTful API
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restsetprofile 70 2020-08-11 05:59:24Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

JSONFILE=${1:-$JSON}

# Assign profile to iRMC/BIOS
showinfo Assigning profile $JSONFILE to $IRMC
SESSION=$(ProfileChange $JSONFILE "$POSTOPTION")
[ -z "$SESSION" ] && error 1 ProfileChange failed

# Wait for session to complete
showinfo Waiting for session $SESSION to terminate - be patient ...
SessionWait $SESSION

# Delete session 
showinfo Cleaning up
SessionDelete $SESSION >/dev/null
