#!/bin/bash
#
# restgetbootmac: Reads out the boot mac address (onboard or lom)
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restgetbootmac 67 2020-08-11 05:26:34Z HMBJOrth $
#
# Funktioniert fuer server mit 2 onboard ports wie RX2540

. ${0%/*}/restoptions
. ${0%/*}/resttool

NIC=${1:-lom} PORT=${2:-1}
[ $NIC = lom ] && (( PORT+=2 ))
${0%/*}/restgetmac -i $IRMC -u $USER -p "$PW" -d $DEBUGLEVEL | grep onboard | awk -v l=$PORT 'NR==l {print $1;exit}'

