#!/bin/bash
#
# restgetversion: tool for display of profile versions 
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restgetversion 76 2020-08-12 16:37:52Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

showinfo "Reading versions from $IRMC ..."
RestGet rest/v1/Oem/eLCM/ProfileManagement/version
