#!/bin/bash
#
# restbootci - Tool for booting custom image from eLCM
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restbootci 70 2020-08-11 05:59:24Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

IMAGE=${1:-$CUSTOMIMAGENAME}

showinfo "Booting >$IMAGE< on $IRMC - this can take a couple of minutes ... "
SESSION=$(CustomImageBoot $IMAGE)
[ -z "$SESSION" ] && error 1 CustomImageBoot failed
showinfo Waiting for session $SESSION to terminate - be patient ...
SessionWait $SESSION
showinfo Done
# Delete session from session list
showinfo Cleaning up
SessionDelete $SESSION >/dev/null
