#!/bin/bash
#
# restsetdeploy: Konfigurieren des Webdownload servers
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restsetdeploy 70 2020-08-11 05:59:24Z HMBJOrth $

[ $0 == bash ] && DIR=. || DIR=${0%/*}
. ${DIR}/restoptions
. ${DIR}/resttool

showinfo Setting Deployment server according to $1 on $IRMC
SESSION=$(RestPut rest/v1/Oem/eLCM/Repository/Deployment --data @$1 | ReadJsonValue '"Id":')
[ -z "$SESSION" ] && error 1 RestPut failed
showinfo "Waiting for session $SESSION (checking connection to deployment server)"
SessionWait $SESSION
showinfo Cleaning up
SessionDelete $SESSION >/dev/null

