#!/bin/bash
#
# restgetdeploy: Auslesen der Konfiguration des Webdownload Servers
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restgetdeploy 70 2020-08-11 05:59:24Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

showinfo "Reading Webdownload server settings on $IRMC ..."
RestGet rest/v1/Oem/eLCM/Repository/Deployment | \
	awk '
		/^HTTP/ { 
				if ($2 != 200) {
					print "HTTP Error: " $2;
					exit;
				}
			}
	     	/^{/     { flag++ }
	      	flag	{ 
				print $0
			}' | sed 's/\\//g'
