#!/bin/bash
#
# restloadeim: Upload des eIM images auf eLCM SD-Card
#
# (c) Juergen Orth - Fujitsu Technology Solutions GmbH
#
# $Id: restloadeim 74 2020-08-12 10:12:36Z HMBJOrth $

. ${0%/*}/restoptions
. ${0%/*}/resttool

OSID=${1:-$DEFAULTOSID}
showinfo Uploading eIM image with OsTypeId $OSID to $IRMC. This can take a very long time ...
SESSION=$(RestPost "rest/v1/Oem/eLCM/SVIM/Download?OSTypeId=$OSID" | ReadJsonValue '"Id":')
[ -z "$SESSION" ] && error 1 ProfileStoreAdd failed
showinfo Waiting for session $SESSION to terminate - be patient ...
SessionWait $SESSION
showinfo Cleaning up
SessionDelete $SESSION >/dev/null

